service: serverless-aluguei-backend

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
functions:
  main:
    handler: dist/index.handler
    events:
      - http:
          method: ANY
          path: /api
          cors: true
      - http:
          method: ANY
          path: /api/{proxy+}
          cors: true